In [1]:
import numpy as np

In [8]:
a1=np.array([1,2,3,4,5])
b1=np.array([6,7,8,9,10])


In [9]:
#horizontal sum
a1.sum()


15

In [10]:
b1.sum()

40

In [29]:
a2=np.array([[11,12,13,14,15],[16,17,18,19,20],[55,56,57,58,59]])
a2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [55, 56, 57, 58, 59]])

In [16]:
ADD horizontally
a2.sum()

155

In [17]:
#ADD vertically
a2.sum(axis=0)

array([27, 29, 31, 33, 35])

In [15]:
#task 2
b2=np.array([[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]])
b2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [23]:
condition=b2<28
print(condition)
less_than=b2[condition]
print(less_than)

[[ True  True  True  True  True]
 [ True  True False False False]
 [False False False False False]]
[21 22 23 24 25 26 27]


In [24]:
condition1=b2>28
greater_than=b2[condition1]
print(greater_than)

[29 30 31 32 33 34 35]


In [25]:
c2=np.array([[36,37,38,39,40],[41,42,43,44,45],[46,47,48,49,50]])

In [30]:
conca_x=np.concatenate((a2,b2,c2),axis=1)
print(conca_x)

[[11 12 13 14 15 21 22 23 24 25 36 37 38 39 40]
 [16 17 18 19 20 26 27 28 29 30 41 42 43 44 45]
 [55 56 57 58 59 31 32 33 34 35 46 47 48 49 50]]


In [31]:
conca_y=np.concatenate((a2,b2,c2),axis=0)
print(conca_y)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [55 56 57 58 59]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
